server:
  port: 8087

spring:
  application:
    name: shipment-service
  datasource:
    url: jdbc:mysql://localhost:3306/shipment?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: MinhLuan.1004
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  jwt:
    secret: "MinhLuanSuperSecretKey_1234567890"
  gateway:
    base-url: "http://localhost:8085"   # dÃ¹ng chá»— khÃ¡c náº¿u cáº§n
  driver:
    base-url: "http://localhost:8085"   # ğŸ‘ˆ ClientsConfig Ä‘á»c giÃ¡ trá»‹ nÃ y

  firebase:
    enabled: true
    # ÄÆ°á»ng dáº«n file service account (Ä‘áº·t file á»Ÿ project root/.smartdelivery-secrets/firebase-admin.json)
    credentials: ${GOOGLE_APPLICATION_CREDENTIALS:.smartdelivery-secrets/firebase-admin.json}
    # URL Realtime Database cá»§a báº¡n (copy tá»« Firebase console)
    db-url: ${FIREBASE_DB_URL:https://smartdelivery-4c34f-default-rtdb.firebaseio.com}
