# src/main/resources/application.yml
server:
  port: 8086

spring:
  application:
    name: driver-service
  datasource:
    url: jdbc:mysql://localhost:3306/driver?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: MinhLuan.1004
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  jwt:
    secret: "MinhLuanSuperSecretKey_1234567890"
  gateway:
    base-url: "http://localhost:8085"

  firebase:
    enabled: true
    # Đường dẫn file service account (đặt file ở project root/.smartdelivery-secrets/firebase-admin.json)
    credentials: ${GOOGLE_APPLICATION_CREDENTIALS:.smartdelivery-secrets/firebase-admin.json}
    # URL Realtime Database của bạn (copy từ Firebase console)
    db-url: ${FIREBASE_DB_URL:https://smartdelivery-4c34f-default-rtdb.firebaseio.com}
